[user]
name = "Madalin Popa"
email = "contact@madalinpopa.com"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[aliases]
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
n = ["new"]

[ui]
editor = "nvim"
default-command = ["st"]
pager = "delta"
diff-formatter = ":git"

[templates]
draft_commit_description = '''
concat(  
  coalesce(description, default_commit_description, "\n"),
  surround(
      "\nJJ: This commit contains the following changes:\n", "",
      indent("JJ:     ", diff.summary()),
    ),
  "\nJJ: ignore-rest\n",
  diff.git()

)
'''
git_push_bookmark = '"branch/push-" ++ change_id.short()'
